### ISSUE TITLE
Scenario Outline inserts are not parsed in Data Tables

### ISSUE THREAD

**Issue by sazzer** [cucumber-rs/gherkin#12]
Given the following scenario:
```
    Scenario Outline: Look up a known username: <Username>
        Given a user exists with details:
            | Username | <Username> |
        When I look up the username '<Username>'
        Then the username does exist

        Examples:
            | Username |
            | known    |
```

The insert `<Username>` from the Examples table works correctly in the Scenario name and in the "When" step, but *not* in the "Given" step. Instead, when parsing the table, I get:
```
[["Username", "<Username>"]]
```

Where I would have expected:
```
[["Username", "known"]]
```

**Comment by bbqsrc** [comment]
This should be fixed in a couple of weeks.

**Comment by wucke13** [comment]
I made a [bug report](https://github.com/bbqsrc/cucumber-rust/issues/86) which likely is related. I need this ASAP. Is there anything I can do to accelerate this, @bbqsrc ?

**Comment by bbqsrc** [comment]
See https://github.com/bbqsrc/cucumber-rust/issues/64 for the current state of this.

**Comment by ilslv** [comment]
@bbqsrc this feature is supported in [`cucumber`][1] crate and described in [`Features`][2] book chapter. I think it's should be handled by consumers of this crate like [`cucumber`][1], rather than expanding right inside parser. 
In case you agree, I think this issue can be closed. 




[1]: https://github.com/cucumber-rs/cucumber
[2]: https://cucumber-rs.github.io/cucumber/main/Features.html#scenario-outline-keyword

**Comment by tyranron** [comment]
I agree with @ilslv about the parser itself doesn't make any substitutions by himself, but rather gives the AST of exactly what has been declared. For [`cucumber`](https://docs.rs/cucumber) this issue has been resolved.

So I close this for now. Feel free to reopen, if needed.
